[pytest]
asyncio_mode = auto
testpaths = app/core/tests app/marketing/tests app/sales/tests app/finance/tests app/admin/tests app/it/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    asyncio: marks tests as async (deselect with '-m "not asyncio"')
